//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int MA_DG { get; set; }
        public Nullable<int> MA_KH { get; set; }
        public Nullable<int> MA_PHONG { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<int> SO_SAO { get; set; }
        public Nullable<System.DateTime> NGAY_DANHGIA { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
