//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAT_PHONG()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
            this.HOA_DON_TAM = new HashSet<HOA_DON_TAM>();
            this.SU_DUNG_DV = new HashSet<SU_DUNG_DV>();
        }
    
        public int MA_DP { get; set; }
        public Nullable<int> MA_KH { get; set; }
        public Nullable<int> MA_PHONG { get; set; }
        public Nullable<System.DateTime> NGAY_DAT { get; set; }
        public Nullable<System.DateTime> NGAY_NHAN { get; set; }
        public Nullable<System.DateTime> NGAY_TRA { get; set; }
        public Nullable<decimal> TIEN_COC { get; set; }
        public string TRANG_THAI { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual PHONG PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON_TAM> HOA_DON_TAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SU_DUNG_DV> SU_DUNG_DV { get; set; }
    }
}
