//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        public int MA_HD { get; set; }
        public Nullable<int> MA_DP { get; set; }
        public Nullable<decimal> TONG_TIEN { get; set; }
        public Nullable<System.DateTime> NGAY_XUAT { get; set; }
        public Nullable<bool> DA_THANH_TOAN { get; set; }
    
        public virtual DAT_PHONG DAT_PHONG { get; set; }
    }
}
