//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        public int MA_NV { get; set; }
        public string HO_TEN { get; set; }
        public string CHUC_VU { get; set; }
        public string SDT { get; set; }
        public Nullable<int> MA_TK { get; set; }
    
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
