//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.ALBUM_ANH_PHONG = new HashSet<ALBUM_ANH_PHONG>();
            this.DANH_GIA = new HashSet<DANH_GIA>();
            this.DAT_PHONG = new HashSet<DAT_PHONG>();
        }
    
        public int MA_PHONG { get; set; }
        public string TEN_PHONG { get; set; }
        public Nullable<int> TANG { get; set; }
        public string TRANG_THAI { get; set; }
        public Nullable<int> MA_LOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALBUM_ANH_PHONG> ALBUM_ANH_PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PHONG> DAT_PHONG { get; set; }
        public virtual LOAI_PHONG LOAI_PHONG { get; set; }
    }
}
