//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLKSEntities : DbContext
    {
        public QLKSEntities()
            : base("name=QLKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALBUM_ANH_PHONG> ALBUM_ANH_PHONG { get; set; }
        public virtual DbSet<DANH_GIA> DANH_GIA { get; set; }
        public virtual DbSet<DAT_PHONG> DAT_PHONG { get; set; }
        public virtual DbSet<DICH_VU> DICH_VU { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<HOA_DON_TAM> HOA_DON_TAM { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<LOAI_PHONG> LOAI_PHONG { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<SU_DUNG_DV> SU_DUNG_DV { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
    
        public virtual int SP_TINH_HOA_DON(Nullable<int> mA_DP)
        {
            var mA_DPParameter = mA_DP.HasValue ?
                new ObjectParameter("MA_DP", mA_DP) :
                new ObjectParameter("MA_DP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TINH_HOA_DON", mA_DPParameter);
        }
    
        public virtual int SP_SU_DUNG_DICH_VU(Nullable<int> mA_DP, Nullable<int> mA_DV, Nullable<int> sO_LUONG)
        {
            var mA_DPParameter = mA_DP.HasValue ?
                new ObjectParameter("MA_DP", mA_DP) :
                new ObjectParameter("MA_DP", typeof(int));
    
            var mA_DVParameter = mA_DV.HasValue ?
                new ObjectParameter("MA_DV", mA_DV) :
                new ObjectParameter("MA_DV", typeof(int));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SU_DUNG_DICH_VU", mA_DPParameter, mA_DVParameter, sO_LUONGParameter);
        }
    }
}
