//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALBUM_ANH_PHONG
    {
        public int MA_ANH { get; set; }
        public Nullable<int> MA_PHONG { get; set; }
        public string LINK_ANH { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
