//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SU_DUNG_DV
    {
        public int MA_SD { get; set; }
        public Nullable<int> MA_DP { get; set; }
        public Nullable<int> MA_DV { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<System.DateTime> NGAY_SU_DUNG { get; set; }
    
        public virtual DAT_PHONG DAT_PHONG { get; set; }
        public virtual DICH_VU DICH_VU { get; set; }
    }
}
